#! /usr/bin/python

import argparse
import os
import csv
import sys
import re
import math

##### UTiLS #####

class RecursiveException(Exception):
    pass

class KTSpreadsheet:
    
    spreadsheet = None
    cells_seen = []
    
    def __init__(self, fullpath):
        if os.path.isdir(fullpath):
            print "Please pass in the path to a CSV file and not a directory."
        elif os.stat(fullpath).st_size == 0:
            print os.stat(fullpath)
            print "The file either does not exist or is empty."
        else:
            # then file exists/isn't empty and we can continue with the parsing
            f = open(fullpath, 'r')
            reader = csv.reader(f)
    
            self.spreadsheet = []
            for i, row in enumerate(reader):
                spreadsheet_row = []
                for cell in row:
                    spreadsheet_row.append(cell.strip())
                self.spreadsheet.append(spreadsheet_row)
            f.close()

    # small utility to convert alphabetic letters to numbers 1-26 (for the column)
    def letter_to_num(self, letter):
        return ord(str.lower(letter)) - ord('a')

    ##### LOGiC #####
    
    ## Handle number operations
    # assuming only one operation
    def handle_num(self, cell_args):
        eval_str = ""
        args = cell_args[0:-1]
        op = cell_args[-1]

        # assuming only single operator is "!" factorial operator
        if len(args) == 1:
          return str(math.factorial(float(args[0])))

        # operators that take 2 or more arguments
        for num_str in args:
            # must convert integer num_str's to floats
            num_str = str(float(num_str))
    
            if eval_str == "":
                # first element
                eval_str += num_str
            else:
                eval_str += cell_args[-1] + num_str
        ret_str = eval(eval_str)
    
        # specific formatting to return integer whenever possible
        # extremely hacky solution to check if float ends in ___.0
        # if so, then convert to int
        if str(ret_str)[-2:] =='.0':
            ret_str = int(ret_str)
        return str(ret_str)
    
    def parse_ref(self, ref):
        col_num = self.letter_to_num(ref[0])
        row_num = int(ref[1:])
        return col_num, row_num
    
    ## Handle cell reference
    # assuming there is only ONE cell reference
    # ** In order to handle circular referencing, breaks a loop and returns -1 after seeing
    #      the initial reference again.
    # ^ Did not need to implement... Just thought about it
    def handle_ref(self, ref):
        if ref in self.cells_seen:
            self.cells_seen.append(ref)
            raise RecursiveException("[" + " -> ".join(self.cells_seen) + "]")
        self.cells_seen.append(ref)
        
        col_num, row_num = self.parse_ref(ref)
    
        ref_cell = self.spreadsheet[row_num-1][col_num]
        new_refs = re.search('[a-z]\d{1,2}', ref_cell, re.IGNORECASE)
        if new_refs:
            ref = new_refs.group()
            this_col_num, this_row_num = self.parse_ref(ref)
            self.spreadsheet[this_row_num-1][this_col_num] = self.handle_ref(ref)
        else:
            return self.spreadsheet[row_num-1][col_num]
    
    
    ## Function that handles evaluation of cells
    # 
    # Input: (Note that all input is originally a string)
    #   int -> strips whitespace and returns integer
    #   eval -> begins with "=". Evaluates value and returns integer
    #   default -> Any other input should not be handled
    #
    # ** needs fullpath because we call read_row in handle_ref
    def eval_cell(self, cell):
        stripped_cell = str.strip(cell)
        valid_ops = {'+': 2, '-': 2, '*': 2, '/': 2, '!': 1}
        op = None
    
        if stripped_cell == "":
            return ""
    
        try:
            if float(stripped_cell):
                # this cell is a number
                return stripped_cell
        except ValueError:
            # Not a float/integer
            if stripped_cell[0] == "=":
                # need to evaluate cell
                # remove '=' from cell
                cell_args = stripped_cell[1:].split()
                for i in range(0, len(cell_args)):
                  arg = cell_args[i]
                  match = re.search("[A-Z][0-9]+", arg)
                  if match != None:
                    # This is a reference cell_arg
                    self.cells_seen = []
                    cell_args[i] = self.handle_ref(arg)
                arg_list = []
                for i in range(0, len(cell_args)):
                  arg = cell_args[i]
                  if arg in valid_ops.keys():
                    number_of_args = valid_ops[arg]
                    op_args = arg_list[len(arg_list)-number_of_args:]
                    arg_list = arg_list[:len(arg_list)-number_of_args]
                    op_args.append(arg)
                    arg_list.append(self.handle_num(op_args))
                  else:
                    arg_list.append(arg)
                if len(arg_list) == 1:
                  return arg_list[0]
                print "AHHHHH IT'S WRONG"
            else:
                print "Improper input. Only handles the floats/ints >= 0 and '=_____' notation"
    
    # Main logic function for spreadsheet evaluator
    def eval_spreadsheet(self):
        for row_index, row in enumerate(self.spreadsheet):
            for cell_index, cell in enumerate(row):
                self.spreadsheet[row_index][cell_index] = self.eval_cell(cell)                    
            
    def print_spreadsheet(self):
        for row in self.spreadsheet:
            sys.stdout.write("\t".join(row) + '\n')


##### MAiN LOOP #####

# code that provides "pretty" command line help and argument checking
parser = argparse.ArgumentParser(description='Simple evaluator for a CSV spreadsheet')
parser.add_argument('csv_file', metavar='CSV_FILE', type=str,
                                help='Input CSV spreadsheet filepath')
args = parser.parse_args()


# find full path rather than relative path for os module's use
fullpath =  os.path.realpath(args.csv_file)
kt_spreadsheet = KTSpreadsheet(fullpath)
try:
    kt_spreadsheet.eval_spreadsheet()
    kt_spreadsheet.print_spreadsheet()
except RecursiveException, e:
    print e.message
